SELECT * FROM Patients WHERE conditions LIKE '% DIAB1%' OR conditions LIKE 'DIAB1%' 

#CONDITION OF PATIENT CAN BE STARTING WITH DIAB1 or IT MAY CONTAIN ANY OTHER CONDITION AND SEPERATED BY SPACE SO '% ' SHOWS ANYTHING BEFORE SPACE STARTING WITH D.